---
title: "ComparingSmoothingReport"
output: html_document
date: "`r Sys.Date()`"
params:
  base_path: "C:/Users/oaw001/OneDrive - University of the Sunshine Coast/PostProcessing"
  species: "Sparkes_Koala"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 8, fig.height = 6)
```

This is for within the species...

Step 1 is to find all the smoothing types that have been tried and load in their data to a consolidated file.
```{r bind, include = FALSE}
metrics_list <- list.files(
  file.path(base_path, "Output", species),
  pattern = "_performance_.*\\.csv$",
  full.names = TRUE
)

metrics <- lapply(metrics_list, function(file) {
  fread(file) %>%
    mutate(smoothing_type = basename(file),
           rep_id = str_split(tools::file_path_sans_ext(basename(file)), "_")[[1]][3]) %>%
    rename(Activity = 1) # rename to Activity in all cases
})

# remove Class: from the Activity and .csv from the smoothing_type
metrics <- rbindlist(metrics) %>%
  mutate(
    Activity = gsub("Class: ", "", Activity), ## also change this between activity and behaviour
    smoothing_type = gsub("_performance_.*\\.csv$", "", smoothing_type)
  ) %>%
  select(!Prevelance) %>%
  na.omit()

metrics <- metrics %>% 
  mutate(smoothing_type = gsub("Smoothing", "", smoothing_type))

# add levels so its easier to plot later
metrics$smoothing_type <- factor(metrics$smoothing_type, levels = c("No", "Mode", "Duration", "Transition", "HMM", "Bayesian"))
```

```{r compare}
# its hard to make any one single judgement, so I can make a plot for now
# 
metrics_long <- metrics %>%
  pivot_longer(cols = c(Precision, Recall, F1, Accuracy),
               names_to = "Metric",
               values_to = "Score")

fwrite(metrics_long, file.path(base_path, "Output", species, "all_smoothed_metrics.csv"))

```

```{r simp_plot, fig.width = 20, fig.height = 20}
# and a simplified plot as 
simplified_metrics <- metrics_long #%>% dplyr::filter(Activity == "Macro-Average")
ggplot(simplified_metrics, aes(x = smoothing_type, y = Score, fill = smoothing_type)) +
  geom_boxplot() +
  facet_wrap(Activity~ Metric, scales = "free_y", nrow = length(unique(simplified_metrics$Activity))) +
  scale_fill_manual(values = my_colours) +
  my_theme() +
  labs(x = "Smoothing Method", y = "Score", fill = "Smoothing Type") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

And now make another version of that:
```{r fig.width = 20, fig.height = 20}
setDT(simplified_metrics)
baseline <- simplified_metrics[
  smoothing_type == "No",
  .(Activity, rep_id, Metric, baseline = Score)
]
df <- merge(
  simplified_metrics,
  baseline,
  by = c("Activity", "rep_id", "Metric"),
  all.x = TRUE
)
df[, relative_change := Score - baseline]

# now plot that
df <- df %>% dplyr::filter(!smoothing_type == "No")
ggplot(df, aes(x = smoothing_type, y = relative_change, fill = smoothing_type)) +
  geom_boxplot() +
  geom_hline(yintercept = 0, linetype = "dotted", colour = "black") +
  my_theme() +
  scale_fill_manual(values = my_colours) +
  labs(x = "Smoothing Type", y = "Relative change to F1 Score") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(Activity~ Metric, nrow = length(unique(simplified_metrics$Activity))) +
  theme(legend.position = "none")

```
